name: Build and Deploy to GitHub Pages - dev

on:
  push:
    branches:
      - dev

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site/decision-table # Specify that website content will be built into the /decision-table subdirectory
          verbose: true

      - name: Ensure _site directory exists
        run: |
          mkdir -p ./_site
          sudo chmod -R 777 ./_site

      - name: Create CNAME file for custom domain
        run: echo 'example.site' > ./_site/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site
          name: github-pages
          retention-days: 1

  report-build-status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Report build status
        run: |
          gh api -X POST "repos/$GITHUB_REPOSITORY/pages/telemetry" \
            -F github_run_id="$GITHUB_RUN_ID" \
            -F conclusion="success"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONCLUSION: success

  deploy:
    needs: [build, report-build-status]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          artifact_name: github-pages
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 600000
          error_count: 10
          reporting_interval: 5000
